[package]
name = "tcp_connection_test"
edition = "2024"
version.workspace = true

[dependencies]
tcp_connection = { path = "../../tcp_connection" }
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
